language: php

php:
  - 7.2

before_install:
  - composer require satooshi/php-coveralls
  - composer install --dev

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate --force
  - php artisan jwt:secret --force
  - php artisan migrate

script:
  - composer test
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
  
after_script:
  - travis_retry php vendor/bin/php-coveralls
  - travis_retry php vendor/bin/php-coveralls -v

notifications:
  email: false
